### ISSUE TITLE
Provide a Flatpak as software package — for Linux systems

### ISSUE THREAD

**Issue by x80486** [anyproto/anytype-ts#74]
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop and desktop applications.

Would be great (and convenient) to be able to install `Anytype` from `Flathub`. It would also acquire _visibility_ in the app stores automatically.

**Comment by Biepa** [comment]
Hey @x80486 
Thank you for the request. If you are a member to the forum, please upvote it here:
https://community.anytype.io/t/alternative-installer-for-linux/985

**Comment by vintprox** [comment]
@Biepa Do you exclusively gather priority by looking into <https://community.anytype.io> forum or you also look in the [Discussions](https://github.com/orgs/anyproto/discussions/25)?

**Comment by fuksman** [comment]
@vintprox the community on GitHub is one day old, so we give it more time to understand how it is best to manage it along with the user community. 
We track requests in both communities. 
For now, feel free to act as it best suits you, and we will notify everyone if there are any changes in the process ☀️

**Comment by x80486** [comment]
This repository holds the actual source code for the client, right? The `README` is accurate, but the repository name is _a little bit off_.

If that's the case, and you are OK publishing to `Flathub`, I could probably take a look and see if I can start the `Flatpak` manifest. Sometimes is better to start by using the `DEB` file, and later try to build it from source — which is the ideal route.

**Comment by ra3orblade** [comment]
@x80486 would be great, if you need help contact me on telegram

**Comment by x80486** [comment]
I have the [application](https://github.com/x80486/flathub/tree/com.anytype.anytype/) working, but I see some errors. For instance, when I try to close the applications using the windows' close button, I see these errors in the journal and the application doesn't actually terminate:

```shell
Jul 22 13:54:11 ubuntu-vm com.anytype.anytype.desktop[125441]: {"level":"INFO","ts":"2023-07-22T13:54:11.650-0400","logger":"common.commonspace.headsync","msg":"sync done:","spaceId":"bafyreicjtx3jp6332op5ocygt6qey7ouedsof7zx5gbi4xbib4voj6qmpu.2fnoe5hiybzqu","newIds":0,"changedIds":0,"removedIds":0,"already deleted ids":0,"peerId":"12D3KooWCywWYgfDZmamJxvWKAvMT5AYDdRG8MMhCpYLHjW8aX7K"}
Jul 22 13:54:20 ubuntu-vm com.anytype.anytype.desktop[125441]: 13:54:20.819 \u203a closeMain: undefined
Jul 22 13:54:20 ubuntu-vm com.anytype.anytype.desktop[125441]: closeMain: undefined
```

![image](https://github.com/anyproto/anytype-ts/assets/34633617/369299bc-905d-49f8-b914-6fceb5518bb6)

It works fine using the `File > Quit` option from the menu.

> Those IDs are not my account (I created one for testing), but I'm not sure if they are meant to be logged either way. Are they public or private?

Besides that, I see everything working fine, though I see some other "suspicious" errors:

```shell
{"level":"INFO","ts":"2023-07-22T14:02:44.280-0400","logger":"common.commonspace.headsync","msg":"sync done:","spaceId":"bafyreicjtx3jp6332op5ocygt6qey7ouedsof7zx5gbi4xbib4voj6qmpu.2fnoe5hiybzqu","newIds":0,"changedIds":0,"removedIds":0,"already deleted ids":0,"peerId":"12D3KooWG7R2VEmeUoyh8vtHUNp6cmKdih7K31a6vDT8BHezgQ1b"}

14:04:07.121 \u203a [Api].exit, relaunch: false
[Api].exit, relaunch: false
14:04:07.137 \u203a {"level":"ERROR","ts":"2023-07-22T14:04:07.134-0400","logger":"anytype-mw-api","msg":"stream eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZWVkIjoibERZbU9xdHoifQ.pi6-tZrkgCITnxCjysZulrfsOkkwqH51C7Vmwy4uEIs interrupted"}

{"level":"ERROR","ts":"2023-07-22T14:04:07.134-0400","logger":"anytype-mw-api","msg":"stream eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZWVkIjoibERZbU9xdHoifQ.pi6-tZrkgCITnxCjysZulrfsOkkwqH51C7Vmwy4uEIs interrupted"}

stopping the library...
library has been successfully stopped

14:04:08.587 \u203a {"level":"ERROR","ts":"2023-07-22T14:04:08.587-0400","logger":"net.transport.yamux","msg":"listener closed with error","localAddr":"[::]:36477","error":"accept tcp [::]:36477: use of closed network connection"}

{"level":"ERROR","ts":"2023-07-22T14:04:08.587-0400","logger":"net.transport.yamux","msg":"listener closed with error","localAddr":"[::]:36477","error":"accept tcp [::]:36477: use of closed network connection"}

14:04:08.634 \u203a [Api].shutdown, relaunch: false
[Api].shutdown, relaunch: false
```

For a _round one_, if everything seems fine on your end, it would be great if:

- There is an SVG application icon — ideally named after the application ID, for instance, `share/icons/hicolor/scalable/apps/com.anytype.anytype.svg`
- You could publish a metainfo info file: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html — I made up one because it's required, but if it comes bundled already it's better

**Comment by ra3orblade** [comment]
@x80486 could you please make a PR with everything that is required to be added? @fuksman Sergey can answer on licensing questions

**Comment by fuksman** [comment]
Hey @x80486, thank you for your activity! 
The software license is available in the repository's root: https://github.com/anyproto/anytype-ts/blob/main/LICENSE.md
Metadata license — CC0-1.0

**Comment by x80486** [comment]
> @x80486 could you please make a PR with everything that is required to be added? @fuksman Sergey can answer on licensing questions

@ra3orblade, the SVG file should come from the `Anytype` team — and bundled correctly, ideally in `share/icons/hicolor/scalable/apps/com.anytype.anytype.svg`. I can wait for this to be released sometime.

Publishing the AppStream MetaInfo file is a really nice-to-have. It streamlines the `Flatpak` manifest, by just installing the required dependencies and placing the "resource" files in the correct locations. AppStream MetaInfo is _generated_ with every release, but for the most part the content is static — except `releases` and `description`. Like I said, I [made one](https://raw.githubusercontent.com/x80486/flathub/com.anytype.anytype/com.anytype.anytype.metainfo.xml) to move things forward, but ideally it should be bundled with any desktop application. The licenses are specified inside this file as well.

> Notice how the filenames are, ideally, named after the _reverse DNS_ convention. I picked up `com.anytype.anytype`...but that's a guess. It's up to the `Anytype` team to confirm if that's the correct ID (based on the reverse DNS) to be used.

**Comment by isle9** [comment]
@x80486 Hey, what's the progress on this issue? Is there a way for me to install it somehow right now?

**Comment by x80486** [comment]
If you follow the link I provided in previous messages you should be able to get a fully functional `Anytype` install. I provided clear instructions in the `README`.

**Comment by isle9** [comment]
> If you follow the link I provided in previous messages you should be able to get a fully functional `Anytype` install. I provided clear instructions in the `README`.

How would I update the app? I'm guessing that the in-app updater doesn't work?

**Comment by x80486** [comment]
In practice, you should install this one for your user (with `--user`) because you are building it in your machine. The auto-updater is not configured yet. Notice this is not published to `Flathub`...yet :sunglasses:

**Comment by isle9** [comment]
> The auto-updater is not configured yet. Notice this is not published to `Flathub`...yet 😎

Yeah, I thought so. That's not going to do it for me then unfortunately. I'd need the app to be up to date at all times.

**Comment by isle9** [comment]
> El mié, 23-08-2023 a las 00:22 -0700, isle9 escribió:
> Yeah, I thought so. That's not going to do it for me then unfortunately. I'd need the app to be up to date at all times.
> Usually you update flatpaks with the flatpak CLI or gnome-software or similar. I don't se a need for a flathub release to include updates within the app...

Yeah, I was thinking of how to update it automatically right now while it's still not on flathub.

**Comment by mystchonky** [comment]
@x80486 how is it going :) ? Do you need any help testing it?

**Comment by dfarnand** [comment]
I managed to build the app with @x80486's repo, but had to make some changes.

To start, the clone command in the readme won't actually work (since its trying to pull from the official github). For anyone attempting this, what you'll actually want to do is:
```
git clone https://github.com/x80486/flathub
cd flathub
git checkout com.anytype.anytype
``` 

The rest of the commands will work, but the app won't open, giving an error about libsecret. I searched a bit and found the same error had appeared in the [bitwarden flatpak](https://github.com/flathub/com.bitwarden.desktop/pull/73/files), so I copied and pasted the exact code from that PR. I also updated it to pull the newest stable version of anytype, as the older version couldn't sync with my newer data from other devices. 

<details><summary>Here is my updated com.anytype.anytype.yaml</summary>

```
app-id: com.anytype.anytype
base: org.electronjs.Electron2.BaseApp
base-version: "22.08"
command: anytype
finish-args:
  - --device=dri
  - --share=ipc
  - --share=network
  - --socket=pulseaudio
  - --socket=wayland
  - --socket=x11
  - --talk-name=org.freedesktop.Notifications
  # Evaluating Permissions
  - --filesystem=xdg-documents
  - --filesystem=xdg-download
  - --filesystem=xdg-music
  - --filesystem=xdg-pictures
modules:
  - name: anytype
    buildsystem: simple
    build-commands:
      # TODO: Build from sources, but first release in this way
      - ar -o -x anytype_amd64.deb
      - tar --extract --file data.tar.xz
      - cp --preserve --recursive opt/* usr/* /app
      - desktop-file-edit --set-key Exec --set-value "/app/bin/anytype %U" /app/share/applications/anytype.desktop
      - desktop-file-edit --set-key Icon --set-value "com.anytype.anytype" /app/share/applications/anytype.desktop
      - install -D --mode 0644 --target-directory /app/share/metainfo/ com.anytype.anytype.metainfo.xml
      - install -D --mode 0644 --target-directory /app/share/icons/hicolor/scalable/apps/ com.anytype.anytype.svg
      - install -D --mode 0755 com.anytype.anytype.sh /app/bin/anytype
    sources:
      - type: file
        dest-filename: anytype_amd64.deb
        only-arches:
          - x86_64
        sha256: 8948f1219939eaa9edef2922e44a7d0b142787e77a383d71d371e89ab219a8e3
        url: https://github.com/anyproto/anytype-ts/releases/download/v0.35.4/anytype_0.35.4_amd64.deb
        # TODO: Integrate x-checker-data
      - type: file
        path: com.anytype.anytype.metainfo.xml
      - type: file
        path: com.anytype.anytype.svg
      - type: script
        commands:
          - export TMPDIR="${XDG_RUNTIME_DIR}/app/${FLATPAK_ID}"
          - exec zypak-wrapper /app/Anytype/anytype "$@"
        dest-filename: com.anytype.anytype.sh
  - name: libsecret
    buildsystem: meson
    config-opts:
    - "-Dmanpage=false"
    - "-Dvapi=false"
    - "-Dgtk_doc=false"
    cleanup:
    - "/bin"
    - "/include"
    - "/lib/pkgconfig"
    - "/share/gir-1.0"
    - "/share/man"
    sources:
    - type: archive
      url: https://download.gnome.org/sources/libsecret/0.20/libsecret-0.20.4.tar.xz
      sha256: 325a4c54db320c406711bf2b55e5cb5b6c29823426aa82596a907595abb39d28
rename-desktop-file: anytype.desktop
runtime: org.freedesktop.Platform
runtime-version: "22.08"
sdk: org.freedesktop.Sdk
separate-locales: false
```
</details> 

Hope this is helpful, I'd love to see this officially on flathub!
